local palette = require("icecube.colors")
local color_ops = require("icecube.color-ops")

return {
	ALEErrorSign = { bg = palette.midnightblue400, fg = palette.salmon500 },
	ALEVirtualTextError = { fg = palette.salmon500 },
	ALEVirtualTextWarning = { fg = palette.orange500 },
	ALEWarningSign = { bg = palette.midnightblue400, fg = palette.orange500 },
	Boolean = { fg = palette.sunsetpurple },
	Character = { fg = palette.sunsetpurple },
	CmpItemAbbrDefault = { fg = palette.grey800 },
	CmpItemAbbrDeprecated = { fg = palette.slateblue650 },
	CmpItemAbbrDeprecatedDefault = { fg = palette.slateblue650 },
	CmpItemAbbrMatchDefault = { fg = palette.grey800 },
	CmpItemAbbrMatchFuzzyDefault = { fg = palette.grey800 },
	CmpItemKindDefault = { fg = palette.seagreen600 },
	CmpItemMenuDefault = { fg = palette.grey800 },
	colorColumn = { bg = palette.midnightblue400 },
	Comment = { fg = palette.slateblue650 },
	Conceal = { bg = palette.black200, fg = palette.slateblue650 },
	Conditional = { fg = palette.skyblue300 },
	Constant = { fg = palette.sunsetpurple },
	CtrlPMatch = { fg = palette.orange500 },
	CtrlPMode1 = { bg = palette.slateblue100, fg = palette.slateblue650 },
	CtrlPMode2 = { bg = palette.grey500, fg = palette.black200 },
	CtrlPPrtCursor = { bg = palette.grey800, fg = palette.black200 },
	Cursor = { bg = palette.grey800, fg = palette.black200 },
	CursorColumn = { bg = palette.midnightblue400 },
	CursorLine = { bg = palette.midnightblue400 },
	CursorLineFold = { bg = palette.midnightblue400, fg = palette.slateblue300 },
	CursorLineNr = { bg = palette.slateblue500, fg = palette.slateblue900 },
	CursorLineSign = { bg = palette.midnightblue400, fg = palette.slateblue300 },
	DapUIBreakpointsCurrentLine = { fg = palette.seagreen800 },
	DapUIBreakpointsDisabledLine = { fg = palette.grey300 },
	DapUIBreakpointsInfo = { fg = palette.seagreen800 },
	DapUIBreakpointsLine = { fg = palette.teal600 },
	DapUIBreakpointsPath = { fg = palette.teal600 },
	DapUICurrentFrameName = { fg = palette.seagreen800 },
	DapUIDecoration = { fg = palette.teal600 },
	DapUIFloatBorder = { fg = palette.teal600 },
	DapUIFrameName = { bg = palette.black200, fg = palette.grey800 },
	DapUILineNumber = { fg = palette.teal600 },
	DapUIModifiedValue = { fg = palette.teal600 },
	DapUIPlayPause = { fg = palette.seagreen800 },
	DapUIRestart = { fg = palette.seagreen800 },
	DapUIScope = { fg = palette.teal600 },
	DapUISource = { fg = palette.hotpink },
	DapUIStepBack = { fg = palette.teal600 },
	DapUIStepInto = { fg = palette.teal600 },
	DapUIStepOut = { fg = palette.teal600 },
	DapUIStepOver = { fg = palette.teal600 },
	DapUIStop = { fg = palette.salmon800 },
	DapUIStoppedThread = { fg = palette.teal600 },
	DapUIThread = { fg = palette.seagreen800 },
	DapUIType = { fg = palette.hotpink },
	DapUIUnavailable = { fg = palette.grey300 },
	DapUIValue = { bg = palette.black200, fg = palette.grey800 },
	DapUIVariable = { bg = palette.black200, fg = palette.grey800 },
	DapUIWatchesEmpty = { fg = palette.salmon800 },
	DapUIWatchesError = { fg = palette.salmon800 },
	DapUIWatchesValue = { fg = palette.seagreen800 },
	Debug = { fg = palette.seagreen600 },
	Define = { fg = palette.orange500 },
	Delimiter = { fg = palette.slateblue400 },
	DiffAdd = { bg = palette.seagreen300 },
	LineCoveragePass = { bg = palette.seagreen300 },
	DiffChange = { bg = palette.seagreen300 },
	DiffDelete = { bg = palette.burgundy },
	DiffText = { bg = palette.seagreen300 },
	Directory = { fg = palette.teal600 },
	EasyMotionShade = { fg = palette.slateblue200 },
	EasyMotionTarget = { fg = palette.seagreen600 },
	EasyMotionTarget2First = { fg = palette.orange500 },
	EasyMotionTarget2Second = { fg = palette.orange500 },
	EndOfBuffer = { fg = palette.mightnightblue600 },
	Error = { bg = palette.black200, fg = palette.salmon500 },
	ErrorMsg = { bg = palette.black200, fg = palette.salmon500 },
	Exception = { fg = palette.skyblue300 },
	Float = { fg = palette.yellow300 },
	FloatBorder = { bg = palette.slateblue100, fg = palette.grey500 },
	FloatTitle = { fg = palette.grey800 },
	FoldColumn = { bg = palette.midnightblue400, fg = palette.slateblue300 },
	Folded = { bg = palette.midnightblue400, fg = palette.slateblue600 },
	Function = { fg = palette.skyblue300 },
	GitGutterAdd = { bg = palette.midnightblue400, fg = palette.seagreen600 },
	GitGutterChange = { bg = palette.midnightblue400, fg = palette.teal600 },
	GitGutterChangeDelete = { bg = palette.midnightblue400, fg = palette.teal600 },
	GitGutterDelete = { bg = palette.midnightblue400, fg = palette.salmon500 },
	Identifier = { fg = palette.white800 },
	Include = { fg = palette.skyblue300 },
	Keyword = { fg = palette.skyblue300 },
	Label = { fg = palette.tan500 },
	LineNr = { bg = palette.midnightblue400, fg = palette.slateblue300 },
	LineNrAbove = { bg = palette.midnightblue400, fg = palette.slateblue300 },
	LineNrBelow = { bg = palette.midnightblue400, fg = palette.slateblue300 },
	Macro = { fg = palette.orange500 },
	MatchBackground = { bg = palette.midnightblue400 },
	MatchParen = { bg = palette.slateblue200, fg = palette.white800 },
	MatchParenCur = { bg = palette.slateblue200, fg = palette.white800 },
	MatchWord = { bg = palette.slateblue200, fg = palette.white800 },
	ModeMsg = { fg = palette.slateblue650 },
	MoreMsg = { fg = palette.seagreen600 },
	MsgSeparator = { bg = palette.grey500, fg = palette.black200 },
	NonText = { fg = palette.mightnightblue600 },
	Normal = { bg = palette.black200, fg = palette.grey800 },
	NormalFloat = { bg = palette.slateblue100, fg = palette.grey800 },
	Operator = { fg = palette.slateblue400 },
	Number = { fg = palette.orange500 },
	Pmenu = { bg = palette.midnightblue400, fg = palette.grey800 },
	PmenuSbar = { bg = palette.slateblue200 },
	PmenuSel = { bg = palette.slateblue600, fg = palette.white800 },
	PmenuThumb = { bg = palette.grey800 },
	PreCondit = { fg = palette.orange500 },
	PreProc = { fg = palette.sunsetpurple },
	Question = { fg = palette.seagreen600 },
	QuickFixLine = { bg = palette.mightnightblue600, fg = palette.grey800 },
	Repeat = { fg = palette.skyblue300 },
	Search = { bg = palette.slateblue300 },
	SignColumn = { bg = palette.midnightblue400, fg = palette.slateblue300 },
	SignifySignAdd = { bg = palette.midnightblue400, fg = palette.seagreen600 },
	SignifySignChange = { bg = palette.midnightblue400, fg = palette.teal600 },
	SignifySignChangeDelete = { bg = palette.midnightblue400, fg = palette.teal600 },
	SignifySignDelete = { bg = palette.midnightblue400, fg = palette.salmon500 },
	SignifySignDeleteFirstLine = { bg = palette.midnightblue400, fg = palette.salmon500 },
	Sneak = { bg = palette.sunsetpurple, fg = palette.black200 },
	SneakScope = { bg = palette.mightnightblue600, fg = palette.slateblue650 },
	Special = { fg = palette.skyblue300 },
	SpecialChar = { fg = palette.seagreen600 },
	SpecialComment = { fg = palette.seagreen600 },
	SpecialKey = { fg = palette.slateblue400 },
	SpellBad = { bg = palette.black200, fg = palette.salmon500 },
	StartifyBracket = { fg = palette.slateblue650 },
	StartifyFile = { fg = palette.teal600 },
	StartifyFooter = { fg = palette.sunsetpurple },
	StartifyHeader = { fg = palette.sunsetpurple },
	StartifyNumber = { fg = palette.seagreen600 },
	StartifyPath = { fg = palette.slateblue650 },
	StartifySection = { fg = palette.skyblue300 },
	StartifySelect = { fg = palette.orange500 },
	StartifySlash = { fg = palette.slateblue650 },
	StartifySpecial = { fg = palette.grey800 },
	StartifyVar = { fg = palette.slateblue650 },
	Statement = { fg = palette.skyblue300 },
	StatusLine = { bg = palette.grey500, fg = palette.black200 },
	StatusLineNC = { bg = palette.black100, fg = palette.slateblue200 },
	StatusLineTerm = { bg = palette.grey500, fg = palette.black200 },
	StatusLineTermNC = { bg = palette.black100, fg = palette.slateblue200 },
	StorageClass = { fg = palette.skyblue300 },
	String = { fg = palette.seagreen600 },
	Structure = { fg = palette.skyblue300 },
	Substitute = { bg = palette.orange500, fg = palette.brown300 },
	SyntasticErrorSign = { bg = palette.midnightblue400, fg = palette.salmon500 },
	SyntasticStyleErrorSign = { bg = palette.midnightblue400, fg = palette.salmon500 },
	SyntasticStyleWarningSign = { bg = palette.midnightblue400, fg = palette.orange500 },
	SyntasticWarningSign = { bg = palette.midnightblue400, fg = palette.orange500 },
	TabLine = { bg = palette.black100, fg = palette.slateblue200 },
	TabLineFill = { bg = palette.black100, fg = palette.slateblue200 },
	TabLineSel = { bg = palette.black200, fg = palette.grey },
	Tag = { fg = palette.seagreen600 },
	TermCursor = { bg = palette.black200, fg = palette.grey800 },
	TermCursorNC = { bg = palette.slateblue650, fg = palette.black200 },
	Title = { fg = palette.orange500 },
	Todo = { bg = palette.seagreen300, fg = palette.seagreen600 },
	ToolbarButton = { bg = palette.black200, fg = palette.grey },
	ToolbarLine = { bg = palette.black100, fg = palette.slateblue200 },
	Type = { fg = palette.skyblue300 },
	Typedef = { fg = palette.skyblue300 },
	Underlined = { fg = palette.skyblue300, underline = false },
	VertSplit = { bg = palette.black100, fg = palette.black100 },
	Visual = { bg = palette.mightnightblue600 },
	VisualNOS = { bg = palette.mightnightblue600 },
	WarningMsg = { bg = palette.black200, fg = palette.salmon500 },
	Whitespace = { fg = palette.mightnightblue600 },
	WildMenu = { bg = palette.tan1000, fg = palette.black200 },
	WinSeparator = { bg = palette.black100, fg = palette.black100 },
	ZenSpace = { bg = palette.salmon500 },
	cssBraces = { fg = palette.grey800 },
	cssClassName = { fg = palette.seagreen600 },
	cssClassNameDot = { fg = palette.grey800 },
	cssPseudoClassId = { fg = palette.seagreen600 },
	cssTagName = { fg = palette.skyblue300 },
	deniteMatched = { fg = palette.grey800 },
	deniteMatchedChar = { fg = palette.orange500 },
	diffAdded = { fg = palette.seagreen600 },
	diffRemoved = { fg = palette.salmon500 },
	graphqlName = { fg = palette.grey800 },
	graphqlOperator = { fg = palette.grey800 },
	helpHyperTextJump = { fg = palette.sunsetpurple },
	htmlArg = { fg = palette.sunsetpurple },
	htmlEndTag = { fg = palette.skyblue300 },
	htmlTag = { fg = palette.skyblue300 },
	icebergALAccentRed = { fg = palette.salmon500 },
	icebergNormalFg = { fg = palette.grey800 },
	jsArrowFunction = { fg = palette.skyblue300 },
	jsClassDefinition = { fg = palette.grey800 },
	jsClassFuncName = { fg = palette.orange500 },
	jsExport = { fg = palette.skyblue300 },
	jsFlowMaybe = { fg = palette.grey800 },
	jsFlowObject = { fg = palette.grey800 },
	jsFlowType = { fg = palette.orange500 },
	jsFuncCall = { fg = palette.grey800 },
	jsFuncName = { fg = palette.orange500 },
	jsFutureKeys = { fg = palette.skyblue300 },
	jsGlobalObjects = { fg = palette.skyblue300 },
	jsModuleKeywords = { fg = palette.skyblue300 },
	jsModuleOperators = { fg = palette.skyblue300 },
	jsNull = { fg = palette.sunsetpurple },
	jsObjectFuncName = { fg = palette.orange500 },
	jsObjectKey = { fg = palette.teal600 },
	jsSuper = { fg = palette.skyblue300 },
	jsTemplateBraces = { fg = palette.seagreen600 },
	jsUndefined = { fg = palette.sunsetpurple },
	jsonQuote = { fg = palette.grey800 },
	luaComment = { fg = palette.slateblue650 },
	luaCommentDelimiter = { fg = palette.slateblue650 },
	luaCond = { fg = palette.skyblue300 },
	luaCondElse = { fg = palette.skyblue300 },
	luaConstant = { fg = palette.sunsetpurple },
	luaError = { bg = palette.black200, fg = palette.salmon500 },
	luaFor = { fg = palette.skyblue300 },
	luaFunc = { fg = palette.teal600 },
	luaFunction = { fg = palette.skyblue300 },
	luaLabel = { fg = palette.skyblue300 },
	luaMetaMethod = { fg = palette.skyblue300 },
	luaNumber = { fg = palette.sunsetpurple },
	luaOperator = { fg = palette.skyblue300 },
	luaParenError = { bg = palette.black200, fg = palette.salmon500 },
	luaRepeat = { fg = palette.skyblue300 },
	luaSpecial = { fg = palette.seagreen600 },
	luaStatement = { fg = palette.skyblue300 },
	luaString = { fg = palette.teal600 },
	luaString2 = { fg = palette.teal600 },
	luaStringDelimiter = { fg = palette.teal600 },
	luaSymbolOperator = { fg = palette.skyblue300 },
	luaTable = { fg = palette.skyblue300 },
	luaTodo = { bg = palette.seagreen300, fg = palette.seagreen600 },
	lualine_a_buffers_active = { bg = palette.seagreen600, fg = palette.grey300 },
	lualine_a_buffers_inactive = { bg = palette.grey, fg = palette.grey300 },
	lualine_a_command = { bg = palette.peach700, fg = palette.grey300 },
	lualine_a_inactive = { bg = palette.grey, fg = palette.grey300 },
	lualine_a_insert = { bg = palette.yellow800, fg = palette.grey300 },
	lualine_a_normal = { bg = palette.seagreen600, fg = palette.grey300 },
	lualine_a_replace = { bg = palette.teal600, fg = palette.grey300 },
	lualine_a_visual = { bg = palette.peach800, fg = palette.grey300 },
	lualine_b_command = { bg = palette.seagreen600, fg = palette.tan800 },
	lualine_b_inactive = { bg = palette.seagreen600, fg = palette.tan800 },
	lualine_b_insert = { bg = palette.seagreen600, fg = palette.tan800 },
	lualine_b_normal = { bg = palette.seagreen600, fg = palette.tan800 },
	lualine_b_replace = { bg = palette.seagreen600, fg = palette.tan800 },
	lualine_b_visual = { bg = palette.seagreen600, fg = palette.tan800 },
	lualine_c_command = { bg = palette.grey300, fg = palette.tan800 },
	lualine_c_inactive = { bg = palette.grey300, fg = palette.tan800 },
	lualine_c_insert = { bg = palette.grey300, fg = palette.tan800 },
	lualine_c_normal = { bg = palette.grey300, fg = palette.tan800 },
	lualine_c_replace = { bg = palette.grey300, fg = palette.tan800 },
	lualine_c_visual = { bg = palette.grey300, fg = palette.tan800 },
	lualine_transitional_lualine_a_b = { bg = palette.seagreen600, fg = palette.grey },
	lualine_z_command = { bg = palette.grey, fg = palette.grey300 },
	lualine_z_diagnostics_error = { fg = palette.salmon500 },
	lualine_z_diagnostics_hint = { fg = palette.slateblue650 },
	lualine_z_diagnostics_info = { fg = palette.teal600 },
	lualine_z_diagnostics_warn = { fg = palette.orange500 },
	lualine_z_inactive = { bg = palette.grey, fg = palette.grey300 },
	lualine_z_insert = { bg = palette.grey, fg = palette.grey300 },
	lualine_z_normal = { bg = palette.grey, fg = palette.grey300 },
	lualine_z_replace = { bg = palette.grey, fg = palette.grey300 },
	lualine_z_visual = { bg = palette.grey, fg = palette.grey300 },
	markdownBold = { fg = palette.seagreen600 },
	markdownCode = { fg = palette.teal600 },
	markdownCodeDelimiter = { fg = palette.teal600 },
	markdownHeadingDelimiter = { fg = palette.slateblue650 },
	markdownRule = { fg = palette.slateblue650 },
	ngxDirective = { fg = palette.skyblue300 },
	nvimAutoEvent = { fg = palette.skyblue300 },
	nvimHLGroup = { fg = palette.skyblue300 },
	nvimMap = { fg = palette.skyblue300 },
	nvimUnmap = { fg = palette.skyblue300 },
	phpVarSelector = { fg = palette.teal600 },
	plug1 = { fg = palette.grey800 },
	plug2 = { fg = palette.teal600 },
	plugDash = { fg = palette.slateblue650 },
	plugMessage = { fg = palette.seagreen600 },
	vim9Comment = { fg = palette.slateblue650 },
	vim9LineComment = { fg = palette.slateblue650 },
	vimAbb = { fg = palette.skyblue300 },
	vimAddress = { fg = palette.sunsetpurple },
	vimAuHighlight = { fg = palette.skyblue300 },
	vimAugroupError = { bg = palette.black200, fg = palette.salmon500 },
	vimAugroupKey = { fg = palette.skyblue300 },
	vimAutoCmd = { fg = palette.skyblue300 },
	vimAutoCmdMod = { fg = palette.seagreen600 },
	vimAutoCmdOpt = { fg = palette.teal600 },
	vimAutoEvent = { fg = palette.skyblue300 },
	vimAutoSet = { fg = palette.skyblue300 },
	vimBehave = { fg = palette.skyblue300 },
	vimBehaveError = { bg = palette.black200, fg = palette.salmon500 },
	vimBehaveModel = { fg = palette.skyblue300 },
	vimBracket = { fg = palette.grey800 },
	vimBufnrWarn = { bg = palette.black200, fg = palette.salmon500 },
	vimCmplxRepeat = { fg = palette.seagreen600 },
	vimCollClassErr = { bg = palette.black200, fg = palette.salmon500 },
	vimCommand = { fg = palette.skyblue300 },
	vimComment = { fg = palette.slateblue650 },
	vimCommentString = { fg = palette.teal600 },
	vimCommentTitle = { fg = palette.orange500 },
	vimCondHL = { fg = palette.skyblue300 },
	vimContinue = { fg = palette.slateblue650 },
	vimCtrlChar = { fg = palette.seagreen600 },
	vimEchoHL = { fg = palette.skyblue300 },
	vimEchoHLNone = { fg = palette.skyblue300 },
	vimElseIfErr = { bg = palette.black200, fg = palette.salmon500 },
	vimElseif = { fg = palette.skyblue300 },
	vimEmbedError = { bg = palette.black200, fg = palette.grey800 },
	vimEnvvar = { fg = palette.orange500 },
	vimErrSetting = { bg = palette.black200, fg = palette.salmon500 },
	vimError = { bg = palette.black200, fg = palette.salmon500 },
	vimEscape = { fg = palette.seagreen600 },
	vimFBVar = { fg = palette.grey800 },
	vimFTCmd = { fg = palette.skyblue300 },
	vimFTError = { bg = palette.black200, fg = palette.salmon500 },
	vimFTOption = { fg = palette.skyblue300 },
	vimFgBgAttrib = { fg = palette.orange500 },
	vimFold = { bg = palette.midnightblue400, fg = palette.slateblue600 },
	vimFunc = { bg = palette.black200, fg = palette.salmon500 },
	vimFuncEcho = { fg = palette.skyblue300 },
	vimFuncKey = { fg = palette.skyblue300 },
	vimFuncName = { fg = palette.skyblue300 },
	vimFuncSID = { fg = palette.orange500 },
	vimFuncVar = { fg = palette.grey800 },
	vimFunction = { fg = palette.orange500 },
	vimFunctionError = { bg = palette.black200, fg = palette.salmon500 },
	vimGroup = { fg = palette.skyblue300 },
	vimGroupAdd = { fg = palette.seagreen600 },
	vimGroupName = { fg = palette.skyblue300 },
	vimGroupRem = { fg = palette.seagreen600 },
	vimGroupSpecial = { fg = palette.seagreen600 },
	vimHLGroup = { fg = palette.skyblue300 },
	vimHLMod = { fg = palette.orange500 },
	vimHiAttrib = { fg = palette.orange500 },
	vimHiAttribList = { bg = palette.black200, fg = palette.salmon500 },
	vimHiBlend = { fg = palette.teal600 },
	vimHiCTerm = { fg = palette.teal600 },
	vimHiClear = { fg = palette.skyblue300 },
	vimHiCtermError = { bg = palette.black200, fg = palette.salmon500 },
	vimHiCtermFgBg = { fg = palette.teal600 },
	vimHiCtermul = { fg = palette.teal600 },
	vimHiGroup = { fg = palette.skyblue300 },
	vimHiGui = { fg = palette.teal600 },
	vimHiGuiFgBg = { fg = palette.teal600 },
	vimHiGuiFont = { fg = palette.teal600 },
	vimHiGuiRgb = { fg = palette.sunsetpurple },
	vimHiKeyError = { bg = palette.black200, fg = palette.salmon500 },
	vimHiNmbr = { fg = palette.sunsetpurple },
	vimHiStartStop = { fg = palette.teal600 },
	vimHiTerm = { fg = palette.teal600 },
	vimHighlight = { fg = palette.skyblue300 },
	vimInsert = { fg = palette.teal600 },
	vimIskSep = { fg = palette.grey800 },
	vimKeyCode = { fg = palette.teal600 },
	vimKeyCodeError = { bg = palette.black200, fg = palette.salmon500 },
	vimKeyword = { fg = palette.skyblue300 },
	vimLet = { fg = palette.skyblue300 },
	vimLetHereDoc = { fg = palette.teal600 },
	vimLetHereDocStart = { fg = palette.seagreen600 },
	vimLetHereDocStop = { fg = palette.seagreen600 },
	vimLineComment = { fg = palette.slateblue650 },
	vimMap = { fg = palette.skyblue300 },
	vimMapBang = { fg = palette.skyblue300 },
	vimMapMod = { fg = palette.grey800 },
	vimMapModErr = { bg = palette.black200, fg = palette.salmon500 },
	vimMapModKey = { fg = palette.seagreen600 },
	vimMark = { fg = palette.sunsetpurple },
	vimMarkNumber = { fg = palette.sunsetpurple },
	vimMenuMod = { fg = palette.grey800 },
	vimMenuName = { fg = palette.orange500 },
	vimMenuNameMore = { fg = palette.orange500 },
	vimMtchComment = { fg = palette.slateblue650 },
	vimNorm = { fg = palette.skyblue300 },
	vimNotFunc = { fg = palette.skyblue300 },
	vimNotPatSep = { fg = palette.teal600 },
	vimNotation = { fg = palette.seagreen600 },
	vimNumber = { fg = palette.sunsetpurple },
	vimOper = { fg = palette.skyblue300 },
	vimOperError = { bg = palette.black200, fg = palette.salmon500 },
	vimOption = { fg = palette.teal600 },
	vimParenSep = { fg = palette.grey800 },
	vimPatSep = { fg = palette.seagreen600 },
	vimPatSepErr = { bg = palette.black200, fg = palette.salmon500 },
	vimPatSepR = { fg = palette.seagreen600 },
	vimPatSepZ = { fg = palette.seagreen600 },
	vimPatSepZone = { fg = palette.teal600 },
	vimPattern = { fg = palette.skyblue300 },
	vimPlainMark = { fg = palette.sunsetpurple },
	vimPlainRegister = { fg = palette.seagreen600 },
	vimRegister = { fg = palette.seagreen600 },
	vimScriptDelim = { fg = palette.slateblue650 },
	vimSearch = { fg = palette.teal600 },
	vimSearchDelim = { fg = palette.skyblue300 },
	vimSep = { fg = palette.grey800 },
	vimSetMod = { fg = palette.teal600 },
	vimSetSep = { fg = palette.skyblue300 },
	vimSetString = { fg = palette.teal600 },
	vimSpecFile = { fg = palette.teal600 },
	vimSpecFileMod = { fg = palette.teal600 },
	vimSpecial = { fg = palette.skyblue300 },
	vimStatement = { fg = palette.skyblue300 },
	vimString = { fg = palette.teal600 },
	vimStringCont = { fg = palette.teal600 },
	vimStringEnd = { fg = palette.teal600 },
	vimSubst = { fg = palette.skyblue300 },
	vimSubst1 = { fg = palette.skyblue300 },
	vimSubstDelim = { fg = palette.grey800 },
	vimSubstFlagErr = { bg = palette.black200, fg = palette.salmon500 },
	vimSubstFlags = { fg = palette.seagreen600 },
	vimSubstSubstr = { fg = palette.seagreen600 },
	vimSubstTwoBS = { fg = palette.teal600 },
	vimSynCase = { fg = palette.skyblue300 },
	vimSynCaseError = { bg = palette.black200, fg = palette.salmon500 },
	vimSynContains = { fg = palette.seagreen600 },
	vimSynError = { bg = palette.black200, fg = palette.salmon500 },
	vimSynKeyContainedin = { fg = palette.seagreen600 },
	vimSynKeyOpt = { fg = palette.seagreen600 },
	vimSynMtchGrp = { fg = palette.seagreen600 },
	vimSynMtchOpt = { fg = palette.seagreen600 },
	vimSynNextgroup = { fg = palette.seagreen600 },
	vimSynNotPatRange = { fg = palette.teal600 },
	vimSynOption = { fg = palette.seagreen600 },
	vimSynPatRange = { fg = palette.teal600 },
	vimSynReg = { fg = palette.skyblue300 },
	vimSynRegOpt = { fg = palette.seagreen600 },
	vimSynRegPat = { fg = palette.teal600 },
	vimSynType = { fg = palette.skyblue300 },
	vimSyncC = { fg = palette.skyblue300 },
	vimSyncError = { bg = palette.black200, fg = palette.salmon500 },
	vimSyncGroup = { fg = palette.skyblue300 },
	vimSyncGroupName = { fg = palette.skyblue300 },
	vimSyncKey = { fg = palette.skyblue300 },
	vimSyncNone = { fg = palette.skyblue300 },
	vimSyntax = { fg = palette.skyblue300 },
	vimTodo = { bg = palette.seagreen300, fg = palette.seagreen600 },
	vimType = { fg = palette.skyblue300 },
	vimUnmap = { fg = palette.skyblue300 },
	vimUserAttrb = { fg = palette.skyblue300 },
	vimUserAttrbCmplt = { fg = palette.skyblue300 },
	vimUserAttrbCmpltFunc = { fg = palette.seagreen600 },
	vimUserAttrbError = { bg = palette.black200, fg = palette.salmon500 },
	vimUserAttrbKey = { fg = palette.teal600 },
	vimUserCmdError = { bg = palette.black200, fg = palette.salmon500 },
	vimUserCommand = { fg = palette.skyblue300 },
	vimUserFunc = { bg = palette.black200, fg = palette.grey800 },
	vimVar = { fg = palette.grey800 },
	vimWarn = { bg = palette.black200, fg = palette.salmon500 },
	vimoperStar = { fg = palette.skyblue300 },
	xmlAttrib = { fg = palette.sunsetpurple },
	xmlAttribPunct = { fg = palette.skyblue300 },
	xmlEndTag = { fg = palette.skyblue300 },
	xmlNamespace = { fg = palette.skyblue300 },
	xmlTag = { fg = palette.skyblue300 },
	xmlTagName = { fg = palette.skyblue300 },
	NeoTreeDirectoryName = { fg = palette.teal500 },
	NeoTreeDirectoryIcon = { fg = palette.teal500 },
	yamlKeyValueDelimiter = { fg = palette.grey800 },
}
