return {
	require("icecube.highlights.core"),
	require("icecube.highlights.diagnostic"),
	require("icecube.highlights.lsp"),
	require("icecube.highlights.indent_blankline"),
	require("icecube.highlights.nvim-tree"),
	require("icecube.highlights.treesitter"),
	require("icecube.highlights.telescope"),
	require("icecube.highlights.symbols-outline"),
	require("icecube.highlights.trouble"),
	require("icecube.highlights.markdown"),
	require("icecube.highlights.nvim-cmp"),
	require("icecube.highlights.which-key"),
	require("icecube.highlights.leap"),
	require("icecube.highlights.gitsigns"),
	require("icecube.highlights.yanky"),
}
