return {
	-- require("icecube.highlights.core"),
	-- require("icecube.highlights.diagnostic"),
	-- require("icecube.highlights.gitsigns"),
	-- require("icecube.highlights.html"),
	-- require("icecube.highlights.indent_blankline"),
	-- require("icecube.highlights.leap"),
	-- require("icecube.highlights.lsp"),
	-- require("icecube.highlights.markdown"),
	-- require("icecube.highlights.nvim-cmp"),
	-- require("icecube.highlights.nvim-tree"),
	-- require("icecube.highlights.symbols-outline"),
	-- require("icecube.highlights.telescope"),
	-- require("icecube.highlights.treesitter"),
	-- require("icecube.highlights.trouble"),
	-- require("icecube.highlights.which-key"),
	-- require("icecube.highlights.yanky"),

	require("icecube.highlights.core"),
	require("icecube.highlights.diagnostic"),
	require("icecube.highlights.gitsigns"),
	require("icecube.highlights.html"),
	require("icecube.highlights.indent_blankline"),
	require("icecube.highlights.leap"),
	require("icecube.highlights.lsp"),
	require("icecube.highlights.markdown"),
	require("icecube.highlights.nvim-cmp"),
	require("icecube.highlights.nvim-tree"),
	require("icecube.highlights.symbols-outline"),
	require("icecube.highlights.telescope"),
	require("icecube.highlights.termdebug"),
	require("icecube.highlights.treesitter"),
	require("icecube.highlights.trouble"),
	require("icecube.highlights.which-key"),
	require("icecube.highlights.yanky"),
}
