local ts_bg = "#1e2132"
local prompt_bg = "#2b3354"
local results_bg = "#21263b"

return {
	TelescopeBorder = { bg = ts_bg, fg = ts_bg },
	TelescopeMatching = { fg = "#a5bf82" },
	TelescopeMultiIcon = { fg = "#89b8c2" },
	TelescopeMultiSelection = { fg = "#84a0c6" },
	TelescopeNormal = { bg = ts_bg, fg = "#cccccc" },
	TelescopePreviewBlock = { fg = "#a093c7" },
	TelescopePreviewBorder = { bg = ts_bg, fg = ts_bg },
	TelescopePreviewCharDev = { fg = "#a093c7" },
	TelescopePreviewDate = { fg = "#89b8c2" },
	TelescopePreviewDirectory = { fg = "#89b8c2" },
	TelescopePreviewExecute = { fg = "#89b8c2" },
	TelescopePreviewGroup = { fg = "#a093c7" },
	TelescopePreviewHyphen = { fg = "#242940" },
	TelescopePreviewLine = { bg = "#272c42" },
	TelescopePreviewLink = { fg = "#a5bf82" },
	TelescopePreviewMatch = { bg = "#e4aa80", fg = "#392313" },
	TelescopePreviewMessage = { bg = ts_bg, fg = "#cccccc" },
	TelescopePreviewMessageFillchar = { bg = ts_bg, fg = "#2b3354" },
	TelescopePreviewNormal = { bg = ts_bg, fg = "#cccccc" },
	TelescopePreviewPipe = { fg = "#a093c7" },
	TelescopePreviewRead = { fg = "#a093c7" },
	TelescopePreviewSize = { fg = "#89b8c2" },
	TelescopePreviewSocket = { fg = "#84a0c6" },
	TelescopePreviewSticky = { fg = "#84a0c6" },
	TelescopePreviewTitle = { bg = "#a5bf82", fg = "#1e2132" },
	TelescopePreviewUser = { fg = "#a093c7" },
	TelescopePreviewWrite = { fg = "#84a0c6" },
	TelescopePromptBorder = { bg = prompt_bg, fg = prompt_bg },
	TelescopePromptCounter = { fg = "#cccccc" },
	TelescopePromptNormal = { bg = prompt_bg, fg = "#cccccc" },
	TelescopePromptPrefix = { fg = "#84a0c6" },
	TelescopePromptTitle = { bg = "#84a0c6", fg = prompt_bg },
	TelescopeResultsBorder = { bg = results_bg, fg = results_bg },
	TelescopeResultsClass = { fg = "#84a0c6" },
	TelescopeResultsComment = { fg = "#6b7089" },
	TelescopeResultsConstant = { fg = "#a093c7" },
	TelescopeResultsDiffAdd = { bg = "#45493e", fg = "#c4c7b5" },
	TelescopeResultsDiffChange = { bg = "#384851", fg = "#b7c5c8" },
	TelescopeResultsDiffDelete = { bg = "#53343b", fg = "#d2b2b2" },
	TelescopeResultsDiffUntracked = { fg = "#242940" },
	TelescopeResultsField = { fg = "#84a0c6" },
	TelescopeResultsFunction = { fg = "#84a0c6" },
	TelescopeResultsIdentifier = { fg = "#89b8c2" },
	TelescopeResultsLineNr = { bg = "#1e2132", fg = "#444b71" },
	TelescopeResultsNormal = { bg = results_bg, fg = "#cccccc" },
	TelescopeResultsNumber = { fg = "#a093c7" },
	TelescopeResultsOperator = { fg = "#84a0c6" },
	TelescopeResultsSpecialComment = { fg = "#a5bf82" },
	TelescopeResultsTitle = { bg = results_bg, fg = results_bg },
	TelescopeResultsVariable = { fg = "#a5bf82" },
	TelescopeSelection = { bg = prompt_bg },
	TelescopeSelectionCaret = { bg = "#272c42" },
	TelescopeTitle = { bg = ts_bg, fg = "#cccccc" },
}
